# Generated by Django 5.1.6 on 2025-02-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_postmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='author_id',
        ),
    ]
